[server]
url = "http://localhost:4100"

[[scm]]
scm = "gitea"
url = "http://localhost:4101"
secret_file = "e2e/secret-gitea.conf"

[[scm]]
scm = "google"
url = "http://localhost:4102"
secret_file = "e2e/secret-google.conf"
