// Code generated by MockGen. DO NOT EDIT.
// Source: ../core/client.go
//
// Generated by this command:
//
//	mockgen -destination=mock_gen.go -source=../core/client.go --package=udm
//

// Package udm is a generated GoMock package.
package udm

import (
	reflect "reflect"

	core "github.com/iszk1215/mora/core"
	gomock "go.uber.org/mock/gomock"
)

// MockAPIClient is a mock of APIClient interface.
type MockAPIClient struct {
	ctrl     *gomock.Controller
	recorder *MockAPIClientMockRecorder
}

// MockAPIClientMockRecorder is the mock recorder for MockAPIClient.
type MockAPIClientMockRecorder struct {
	mock *MockAPIClient
}

// NewMockAPIClient creates a new mock instance.
func NewMockAPIClient(ctrl *gomock.Controller) *MockAPIClient {
	mock := &MockAPIClient{ctrl: ctrl}
	mock.recorder = &MockAPIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPIClient) EXPECT() *MockAPIClientMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockAPIClient) Do(method, path string, in, out any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", method, path, in, out)
	ret0, _ := ret[0].(error)
	return ret0
}

// Do indicates an expected call of Do.
func (mr *MockAPIClientMockRecorder) Do(method, path, in, out any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockAPIClient)(nil).Do), method, path, in, out)
}

// ListRepositories mocks base method.
func (m *MockAPIClient) ListRepositories() ([]core.Repository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRepositories")
	ret0, _ := ret[0].([]core.Repository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRepositories indicates an expected call of ListRepositories.
func (mr *MockAPIClientMockRecorder) ListRepositories() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRepositories", reflect.TypeOf((*MockAPIClient)(nil).ListRepositories))
}
