// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/csrf": {
            "get": {
                "description": "Generate and return a CSRF token via cookie and JSON body",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Get CSRF token",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/auth/login": {
            "post": {
                "description": "Authenticate with a username and password, creating a session",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Log in with username and password",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.PasswordLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/config": {
            "get": {
                "description": "Return server configuration (e.g. site name)",
                "tags": [
                    "server"
                ],
                "summary": "Get server config",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.ConfigResponse"
                        }
                    }
                }
            }
        },
        "/api/coverages/{trackerId}": {
            "get": {
                "description": "Return coverage history for a tracker (public list endpoint)",
                "tags": [
                    "coverage"
                ],
                "summary": "List coverages for a tracker",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Tracker ID",
                        "name": "trackerId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/coverage.CoverageListResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Upload coverage entries for a repository linked to a tracker",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "coverage"
                ],
                "summary": "Upload coverage data",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Tracker ID",
                        "name": "trackerId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Coverage data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/coverage.CoverageUploadRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/coverage.Coverage"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/coverages/{trackerId}/preview": {
            "get": {
                "description": "Return coverage timeline data as virtual series for a tracker",
                "tags": [
                    "coverage"
                ],
                "summary": "Preview coverage data",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Tracker ID",
                        "name": "trackerId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tracker.PreviewResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/coverages/{trackerId}/{id}/{entry}/files": {
            "get": {
                "description": "Return the file list and metadata for a coverage entry",
                "tags": [
                    "coverage"
                ],
                "summary": "List files in a coverage entry",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Tracker ID",
                        "name": "trackerId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Coverage index",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Entry name",
                        "name": "entry",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/coverage.FileListResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/coverages/{trackerId}/{id}/{entry}/files/{filepath}": {
            "get": {
                "description": "Return the source code and coverage blocks for a file in an entry",
                "tags": [
                    "coverage"
                ],
                "summary": "Get a source file",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Tracker ID",
                        "name": "trackerId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Coverage index",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Entry name",
                        "name": "entry",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "File path",
                        "name": "filepath",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/coverage.CodeResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/me": {
            "get": {
                "description": "Return the current session user, or 204 if not logged in",
                "tags": [
                    "server"
                ],
                "summary": "Get current user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.User"
                        }
                    },
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/api/providers": {
            "get": {
                "description": "Return configured SCM repository managers and their login status",
                "tags": [
                    "server"
                ],
                "summary": "List SCM providers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/server.RepositoryManagerResponse"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/repos": {
            "get": {
                "description": "List repositories the current session can access",
                "tags": [
                    "server"
                ],
                "summary": "List repositories",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/core.Repository"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/repos/{repo_id}/udm/metrics": {
            "get": {
                "description": "Return all UDM metrics for the repository",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "udm"
                ],
                "summary": "List metrics",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Repository ID",
                        "name": "repo_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/udm.ListMetricsResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new UDM metric for the repository",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "udm"
                ],
                "summary": "Create a metric",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Repository ID",
                        "name": "repo_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Metric information",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/udm.MetricModel"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/udm.MetricModel"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/repos/{repo_id}/udm/metrics/{metricId}": {
            "delete": {
                "description": "Delete a UDM metric and its items",
                "tags": [
                    "udm"
                ],
                "summary": "Delete a metric",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Repository ID",
                        "name": "repo_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Metric ID",
                        "name": "metricId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/repos/{repo_id}/udm/metrics/{metricId}/items": {
            "get": {
                "description": "Return all UDM items for a metric",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "udm"
                ],
                "summary": "List items",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Repository ID",
                        "name": "repo_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Metric ID",
                        "name": "metricId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/udm.ListItemsResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new UDM item for a metric",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "udm"
                ],
                "summary": "Create an item",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Repository ID",
                        "name": "repo_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Metric ID",
                        "name": "metricId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Item information",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/udm.ItemModel"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/udm.ItemModel"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/repos/{repo_id}/udm/metrics/{metricId}/items/{itemId}": {
            "delete": {
                "description": "Delete a UDM item and its values",
                "tags": [
                    "udm"
                ],
                "summary": "Delete an item",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Repository ID",
                        "name": "repo_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Metric ID",
                        "name": "metricId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Item ID",
                        "name": "itemId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/repos/{repo_id}/udm/metrics/{metricId}/items/{itemId}/values": {
            "get": {
                "description": "Return all values for a UDM item",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "udm"
                ],
                "summary": "List values",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Repository ID",
                        "name": "repo_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Metric ID",
                        "name": "metricId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Item ID",
                        "name": "itemId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/udm.ListValuesResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Add a value to a UDM item",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "udm"
                ],
                "summary": "Add a value",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Repository ID",
                        "name": "repo_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Metric ID",
                        "name": "metricId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Item ID",
                        "name": "itemId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Value information",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/udm.ValueModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/udm.ValueModel"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete all values for a UDM item",
                "tags": [
                    "udm"
                ],
                "summary": "Delete all values",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Repository ID",
                        "name": "repo_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Metric ID",
                        "name": "metricId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Item ID",
                        "name": "itemId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/signup/cancel": {
            "post": {
                "description": "Cancel the pending signup for the current session",
                "tags": [
                    "auth"
                ],
                "summary": "Cancel pending signup",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/signup/confirm": {
            "post": {
                "description": "Create a user from the pending signup and log in",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Confirm pending signup",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/server.User"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/signup/pending": {
            "get": {
                "description": "Return the pending signup information for the current session",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Get pending signup",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.PendingSignupResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/trackers": {
            "get": {
                "description": "Return trackers owned, edited, or liked by the current user",
                "tags": [
                    "tracker"
                ],
                "summary": "List trackers for current user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tracker.ListTrackersResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Add a new tracker. The name must be unique. Creator becomes owner.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tracker"
                ],
                "summary": "Create a tracker",
                "parameters": [
                    {
                        "description": "Tracker information",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tracker.CreateTrackerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/tracker.TrackerModel"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/trackers/{trackerId}": {
            "get": {
                "description": "Return a single tracker by ID",
                "tags": [
                    "tracker"
                ],
                "summary": "Get a tracker",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Tracker ID",
                        "name": "trackerId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tracker.TrackerResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete the specified tracker. Child series and values are also cascade-deleted.",
                "tags": [
                    "tracker"
                ],
                "summary": "Delete a tracker",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Tracker ID",
                        "name": "trackerId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update tracker fields (e.g. visibility). Requires edit permission.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tracker"
                ],
                "summary": "Update a tracker",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Tracker ID",
                        "name": "trackerId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Fields to update",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tracker.PatchTrackerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tracker.TrackerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/trackers/{trackerId}/like": {
            "post": {
                "description": "Add a like to the specified tracker for the current user",
                "tags": [
                    "tracker"
                ],
                "summary": "Like a tracker",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Tracker ID",
                        "name": "trackerId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove a like from the specified tracker for the current user",
                "tags": [
                    "tracker"
                ],
                "summary": "Unlike a tracker",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Tracker ID",
                        "name": "trackerId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/trackers/{trackerId}/preview": {
            "get": {
                "description": "Return tracker info, all series, and latest values (up to 20 per series) for card previews",
                "tags": [
                    "tracker"
                ],
                "summary": "Preview tracker data",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Tracker ID",
                        "name": "trackerId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tracker.PreviewResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/trackers/{trackerId}/series": {
            "get": {
                "description": "Return all series belonging to the specified tracker",
                "tags": [
                    "tracker"
                ],
                "summary": "List all series",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Tracker ID",
                        "name": "trackerId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tracker.ListSeriesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Add a new series under a tracker. data_type must be \"int\" or \"float\" (defaults to \"float\").",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tracker"
                ],
                "summary": "Create a series",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Tracker ID",
                        "name": "trackerId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Series information",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tracker.CreateSeriesRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/tracker.SeriesModel"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/trackers/{trackerId}/series/{seriesId}": {
            "delete": {
                "description": "Delete the specified series. Child values are also cascade-deleted.",
                "tags": [
                    "tracker"
                ],
                "summary": "Delete a series",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Tracker ID",
                        "name": "trackerId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Series ID",
                        "name": "seriesId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update fields of a series (e.g. data_type, config). Requires edit permission.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tracker"
                ],
                "summary": "Update a series",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Tracker ID",
                        "name": "trackerId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Series ID",
                        "name": "seriesId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Fields to update",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tracker.PatchSeriesRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tracker.SeriesModel"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/trackers/{trackerId}/series/{seriesId}/values": {
            "get": {
                "description": "Return time-series data for the specified series. The limit parameter restricts the maximum number of results.",
                "tags": [
                    "tracker"
                ],
                "summary": "List all values",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Tracker ID",
                        "name": "trackerId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Series ID",
                        "name": "seriesId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Maximum number of results",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tracker.ListValuesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Add time-series data to a series. Duplicate timestamps within the same series are not allowed.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tracker"
                ],
                "summary": "Add a value",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Tracker ID",
                        "name": "trackerId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Series ID",
                        "name": "seriesId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Value data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tracker.CreateValueRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/tracker.ValueModel"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete all time-series data for the specified series",
                "tags": [
                    "tracker"
                ],
                "summary": "Delete all values",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Tracker ID",
                        "name": "trackerId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Series ID",
                        "name": "seriesId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/user/me/api-keys": {
            "get": {
                "description": "Return API keys for the current user",
                "tags": [
                    "api-key"
                ],
                "summary": "List API keys",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/server.UserAPIKey"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new API key for the current user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "api-key"
                ],
                "summary": "Create an API key",
                "parameters": [
                    {
                        "description": "API key name",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.CreateAPIKeyRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/server.CreateAPIKeyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/user/me/api-keys/{keyId}": {
            "delete": {
                "description": "Revoke an API key by ID",
                "tags": [
                    "api-key"
                ],
                "summary": "Revoke an API key",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "API key ID",
                        "name": "keyId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "core.ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "core.Repository": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "scm_id": {
                    "type": "integer"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "coverage.CodeResponse": {
            "type": "object",
            "properties": {
                "blocks": {
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        }
                    }
                },
                "code": {
                    "type": "string"
                },
                "filename": {
                    "type": "string"
                },
                "repo": {
                    "$ref": "#/definitions/core.Repository"
                }
            }
        },
        "coverage.Coverage": {
            "type": "object",
            "properties": {
                "entries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/coverage.CoverageEntry"
                    }
                },
                "id": {
                    "type": "integer",
                    "format": "int64"
                },
                "repoID": {
                    "type": "integer",
                    "format": "int64"
                },
                "revision": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "coverage.CoverageEntry": {
            "type": "object",
            "properties": {
                "hits": {
                    "type": "integer"
                },
                "lines": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "profiles": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/profile.Profile"
                    }
                }
            }
        },
        "coverage.CoverageEntryUploadRequest": {
            "type": "object",
            "properties": {
                "entry": {
                    "type": "string"
                },
                "hits": {
                    "type": "integer"
                },
                "lines": {
                    "type": "integer"
                },
                "profiles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/profile.Profile"
                    }
                }
            }
        },
        "coverage.CoverageListResponse": {
            "type": "object",
            "properties": {
                "coverages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/coverage.CoverageResponse"
                    }
                },
                "repo": {
                    "$ref": "#/definitions/core.Repository"
                }
            }
        },
        "coverage.CoverageResponse": {
            "type": "object",
            "properties": {
                "entries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/coverage.CoverageEntry"
                    }
                },
                "index": {
                    "type": "integer"
                },
                "revision": {
                    "type": "string"
                },
                "revision_url": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "coverage.CoverageUploadRequest": {
            "type": "object",
            "properties": {
                "entries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/coverage.CoverageEntryUploadRequest"
                    }
                },
                "revision": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "coverage.FileListResponse": {
            "type": "object",
            "properties": {
                "files": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/coverage.FileResponse"
                    }
                },
                "meta": {
                    "$ref": "#/definitions/coverage.MetaResponse"
                },
                "repo": {
                    "$ref": "#/definitions/core.Repository"
                }
            }
        },
        "coverage.FileResponse": {
            "type": "object",
            "properties": {
                "filename": {
                    "type": "string"
                },
                "hits": {
                    "type": "integer"
                },
                "lines": {
                    "type": "integer"
                }
            }
        },
        "coverage.MetaResponse": {
            "type": "object",
            "properties": {
                "hits": {
                    "type": "integer"
                },
                "lines": {
                    "type": "integer"
                },
                "revision": {
                    "type": "string"
                },
                "revision_url": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "profile.Profile": {
            "type": "object",
            "properties": {
                "blocks": {
                    "description": "StartLine, EndLine, Count",
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        }
                    }
                },
                "filename": {
                    "type": "string"
                },
                "hits": {
                    "type": "integer"
                },
                "lines": {
                    "type": "integer"
                }
            }
        },
        "server.ConfigResponse": {
            "type": "object",
            "properties": {
                "site_name": {
                    "type": "string"
                }
            }
        },
        "server.CreateAPIKeyRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "server.CreateAPIKeyResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "key": {
                    "type": "string"
                },
                "key_prefix": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "server.PasswordLoginRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "server.PendingSignupResponse": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "server.RepositoryManagerResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "logined": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "server.User": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "server.UserAPIKey": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "key_prefix": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "tracker.CreateSeriesRequest": {
            "type": "object",
            "properties": {
                "config": {
                    "type": "string"
                },
                "data_type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "tracker.CreateTrackerRequest": {
            "type": "object",
            "properties": {
                "chart_config": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "repo_id": {
                    "description": "required if type=\"coverage\"",
                    "type": "integer"
                },
                "type": {
                    "description": "\"tracker\" or \"coverage\", defaults to \"tracker\"",
                    "type": "string"
                },
                "visibility": {
                    "description": "required: \"public\"|\"private\"",
                    "type": "string"
                }
            }
        },
        "tracker.CreateValueRequest": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "tracker.ListSeriesResponse": {
            "type": "object",
            "properties": {
                "series": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/tracker.SeriesModel"
                    }
                },
                "tracker": {
                    "$ref": "#/definitions/tracker.TrackerResponse"
                }
            }
        },
        "tracker.ListTrackersResponse": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "per_page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "trackers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/tracker.TrackerResponse"
                    }
                }
            }
        },
        "tracker.ListValuesResponse": {
            "type": "object",
            "properties": {
                "series": {
                    "$ref": "#/definitions/tracker.SeriesModel"
                },
                "values": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/tracker.ValueModel"
                    }
                }
            }
        },
        "tracker.PatchSeriesRequest": {
            "type": "object",
            "properties": {
                "config": {
                    "type": "string"
                },
                "data_type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "tracker.PatchTrackerRequest": {
            "type": "object",
            "properties": {
                "chart_config": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "visibility": {
                    "type": "string"
                }
            }
        },
        "tracker.PreviewResponse": {
            "type": "object",
            "properties": {
                "series": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/tracker.PreviewSeriesValues"
                    }
                },
                "tracker": {
                    "$ref": "#/definitions/tracker.TrackerResponse"
                }
            }
        },
        "tracker.PreviewSeriesValues": {
            "type": "object",
            "properties": {
                "series": {
                    "$ref": "#/definitions/tracker.SeriesModel"
                },
                "values": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/tracker.ValueModel"
                    }
                }
            }
        },
        "tracker.SeriesModel": {
            "type": "object",
            "properties": {
                "config": {
                    "type": "string"
                },
                "data_type": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "tracker_id": {
                    "type": "integer"
                }
            }
        },
        "tracker.TrackerModel": {
            "type": "object",
            "properties": {
                "chart_config": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "repo_id": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                },
                "visibility": {
                    "type": "string"
                }
            }
        },
        "tracker.TrackerResponse": {
            "type": "object",
            "properties": {
                "chart_config": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "like_count": {
                    "type": "integer"
                },
                "liked": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "repo_id": {
                    "type": "integer"
                },
                "role": {
                    "description": "\"\" | \"owner\" | \"editor\"",
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "visibility": {
                    "description": "\"public\" | \"private\"",
                    "type": "string"
                }
            }
        },
        "tracker.ValueModel": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "seriesId": {
                    "type": "integer"
                },
                "time": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "udm.ItemModel": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "metric_id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/udm.ValueType"
                }
            }
        },
        "udm.ListItemsResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/udm.ItemModel"
                    }
                },
                "metric": {
                    "$ref": "#/definitions/udm.MetricModel"
                },
                "repo": {
                    "$ref": "#/definitions/core.Repository"
                }
            }
        },
        "udm.ListMetricsResponse": {
            "type": "object",
            "properties": {
                "metrics": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/udm.MetricModel"
                    }
                },
                "repo": {
                    "$ref": "#/definitions/core.Repository"
                }
            }
        },
        "udm.ListValuesResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "$ref": "#/definitions/udm.ItemModel"
                },
                "repo": {
                    "$ref": "#/definitions/core.Repository"
                },
                "values": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/udm.ValueModel"
                    }
                }
            }
        },
        "udm.MetricModel": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "repo_id": {
                    "type": "integer"
                }
            }
        },
        "udm.ValueModel": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "itemId": {
                    "type": "integer"
                },
                "time": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "udm.ValueType": {
            "type": "integer",
            "enum": [
                1
            ],
            "x-enum-varnames": [
                "ValueTypeInt"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Mora API",
	Description:      "Mora is a code coverage tracker API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
